version: '3'

services:
  web:
    image: openjdk:11
    ports:
      - "8080:8080"
    volumes:
      - ./your-application.jar:/app/your-application.jar
    command: ["java", "-jar", "/app/your-application.jar"]
